### ISSUE TITLE
 [Enhancement] Add New Features

### ISSUE THREAD

**Issue by putra4648** [fikrimaulidan99/About_Me_Lesson2#1]
Tambah fitur yg GG dong bang

**Comment by fikrimaulidan99** [comment]
> 
> 
> Tambah fitur yg GG dong bang

sabar-sabar  (O_O;)

Gw masih belajar di Udacity     ______φ(．．)

Cita-cita gw nanti bikin aplikasi yg layak masuk trending playstore, tunggu aje ye (*￣▽￣)b

btw Repo lu yg Manga App nggak compatible pas gw run. Apa gw harus ngoding di linux ya? (￣ω￣;)

**Comment by putra4648** [comment]
Njirr ya gak juga lah  
Lupa gw itu yg manga udah lama blm di upgrade
